### ISSUE TITLE
Do we need sympy for orthonormalization?

### ISSUE THREAD

**Issue by ameya98** [e3nn/e3nn-jax#15]
Talking about this specific function: https://github.com/e3nn/e3nn-jax/blob/main/e3nn_jax/_symmetric_powers.py#L102

**Comment by ameya98** [comment]
and elsewhere in this file?

**Comment by mariogeiger** [comment]
_symmetric_powers use a lot sympy otherwise spherical_harmonics too

**Comment by ameya98** [comment]
Hmm I wonder if we can use some native JAX code instead. Will be much faster.

**Comment by mariogeiger** [comment]
`_symmetric_powers` is a draft for now :). The idea is to generate polynomials in an exact form to then later evaluate them, so we don't really need to be super fast. But it's true that right now the code is so slow that it takes too long to do anything useful with.
`sympy` allows you to be sure about the result you get: you will not get `1e-16` instead of `0`.
As long as we can get exact expression at the end of the process it is fine to me to use floating point operations in between. I know that one way to go is to use `fractions.Fraction.limit_denominator` to round up the floating point values back to exact expression when we know that the result should be of the form of `a/b` or `sqrt(a/b)`

**Comment by ameya98** [comment]
I see! What do we use these calculations for?
I get the advantages of symbolic computation but do we really need exact coefficients? What if we simply dropped all coefficients with norm <= 1e-6?

**Comment by mariogeiger** [comment]
There is no clear usage of these functions for now. Yes rounding to 0 small values is an option. `fractions.Fraction.limit_denominator` does that and also does a bit more.

**Comment by ameya98** [comment]
I think some functions (orthonormalisation) can be rewritten without symbolic computation instead. What do you plan to use these functions for in the future? Just for context.

**Comment by mariogeiger** [comment]
The aim is to create a versatile class like TensorProduct but that is able to provide higher degree polynomials that respect some given symmetries of permutation of the arguments
