### ISSUE TITLE
Code coverage not working

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn-jax#65]
@SauravMaheshkar Any idea why the code coverage is not working?
I believe it happened when we transitioned from `setup.py` to `pyproject.toml`.

https://coveralls.io/github/e3nn/e3nn-jax?branch=main

**Comment by SauravMaheshkar** [comment]
Huh, interesting maybe I missed some key value while porting. 

PS: `pyproject.toml` itself isn't the problem. PyTorch Geometric has up-to-date coverage with coveralls using `pyproject.toml`. Taking a look rn.

**Comment by SauravMaheshkar** [comment]
I looked at the changes made in a older PR which is by far the only file which updated coverage configuration viz. https://github.com/e3nn/e3nn-jax/pull/51 It might be because of the way coverage is being called atm. viz.

https://github.com/e3nn/e3nn-jax/blob/8c502c1046f5121a1c77cf71eccfa1dbbc71ef5d/.github/workflows/tests.yml#L42

@mariogeiger does this invocation seem correct to you ?

**Comment by SauravMaheshkar** [comment]
I'll keep looking 😓

**Comment by SauravMaheshkar** [comment]
I have no clue why this is happening. Any ideas @mariogeiger ?

**Comment by mariogeiger** [comment]
No, let's give up this feature for now

**Comment by SauravMaheshkar** [comment]
Are you referring to adding back the `.coveragerc` or dropping `coverage` monitoring?

**Comment by mariogeiger** [comment]
I meant dropping the monitoring. Because now we are showing a wrong and bad coverage at the first line of the readme 😂

**Comment by SauravMaheshkar** [comment]
True :) I'd say no need for a PR. Maybe you can just update `main` and close the issue for later inspection 🤷🏻‍♂️
