### ISSUE TITLE
Add custom initialization options in e3nn_jax.flax.Linear

### ISSUE THREAD

**Issue by chen-zz20** [e3nn/e3nn-jax#77]
# Description:
Currently, the `e3nn_jax.flax.Linear` module lacks flexibility in providing custom initialization options. This limitation prevents users from initializing network weights according to specific requirements, potentially impacting model performance and convergence speed.

# Expected Outcome:
It is desired to add an option in the `e3nn_jax.flax.Linear` module that allows users to pass a custom initialization function or parameters. This would enable more control over the weight initialization process.
**Proposed Solution:**
1. Add a new parameter named `initializer` to the constructor of `e3nn_jax.flax.Linear` that can accept either a function or a dictionary specifying the initialization method and its parameters.
2. Use the provided `initializer` parameter within the module's `__init__` method to initialize the weights.

# Current Code:
In e3nn_jax.flax.linear, the code is:
```python
def param(name, shape, std, dtype):
    return self.param(
        name, flax.linen.initializers.normal(stddev=std), shape, dtype
    )
```
But when I want to use uniform initializer, I can't do it unless I modify the code of e3nn_jax. So can the option to change the initialization method be added to the official implementation? Thank you!

# References:
- Current documentation of `e3nn_jax.flax.Linear`: [e3nn_jax.flax.Linear](https://e3nn-jax.readthedocs.io/en/latest/_autosummary/e3nn_jax.flax.Linear.html)

**Comment by AdaaaWang** [comment]
A related issue: the "instructions" parameter for Linear is also encapsulated inside e3nn_jax.flax.Linear or e3nn_jax.haiku.Linear, while under some circumstances we wish to customize "instructions" ourselves, for example, in https://github.com/mzjb/xDeepH/blob/main/xdeeph/tr_modules.py#L217-L236.

**Comment by ameya98** [comment]
The custom initializer is very doable; I can get to it next week. The version of TP with instructions exists in the [legacy code](https://github.com/e3nn/e3nn-jax/blob/main/e3nn_jax/_src/legacy/core_tensor_product.py) and should work but is unlikely to come back to the main API because of efficiency reasons.

**Comment by AdaaaWang** [comment]
Thank you so much! Looking forward to it!(By the way, is the efficiency problem in the legacy code caused by the order of tensor contraction, or is it just about doing tensor products?)

**Comment by ameya98** [comment]
@AdaaaWang I completely misunderstood your request for instructions in Linear; I thought you were talking about the tensor product. I have added support for custom initializers and custom instructions in #78! Should merge that in soon; see the tests for how to use these features (`parameter_initializer` and `instructions` respectively).

**Comment by chen-zz20** [comment]
Thank you very much. Looking forward to the new version!

**Comment by ameya98** [comment]
New version has been pushed! See https://github.com/e3nn/e3nn-jax/blob/main/tests/_src/linear_flax_test.py#L32 for an example of how to use custom initializers. Let me know if you need more information to be passed to the initializing function.

https://github.com/e3nn/e3nn-jax/blob/main/tests/_src/linear_flax_test.py#L64 has an example with custom instructions (doesn't support multiple channels for now, and requires the input irreps match exactly because the instructions are passed as 2-tuples of indices).

**Comment by AdaaaWang** [comment]
> @AdaaaWang I completely misunderstood your request for instructions in Linear; I thought you were talking about the tensor product. I have added support for custom initializers and custom instructions in #78! Should merge that in soon; see the tests for how to use these features (`parameter_initializer` and `instructions` respectively).

Thanks very much and sorry for not stating the problem clearly. Looking forward to the new version too! (Besides, I will be very grateful if there is also an instruction option for tensor products.)
